-- insert into  distance ( id, distance,from_city,to_city)
-- values (1,1000,'Moscow','Samara');
-- insert into  distance ( id, distance,from_city,to_city)
-- values (2,1000,'Samara','Moscow');
-- insert into  distance ( id, distance,from_city,to_city)
-- values (3,18,'Samara','Novokuibishevsk');
-- insert into  distance ( id, distance,from_city,to_city)
-- values (4,18,'Novokuibishevsk','Samara');
-- insert into  distance ( id, distance,from_city,to_city)
-- values (5,1018,'Moscow','Novokuibishevsk');
-- insert into  distance ( id, distance,from_city,to_city)
-- values (6,1018,'Novokuibishevsk','Moscow');